import {
  Image,
  Type,
  Images,
  CircleDollarSign,
  HandCoins,
  Users,
  Ticket,
  CalendarDays,
  Gavel,
  Globe,
  BarChart3,
  Hash,
  Quote,
  HelpCircle,
  Video,
  MousePointerClick,
  PanelBottom,
  Columns2,
  ListOrdered,
  Timer,
  Sparkles,
  QrCode,
  AppWindow,
  Newspaper,
  PieChart,
  FileText,
  Gift,
  Trophy,
  Square,
  type LucideIcon,
} from "lucide-react";
import { BLOCK_REGISTRY, type BlockType } from "@donation/blocks";

const MAP: Record<string, LucideIcon> = {
  Image,
  Type,
  Images,
  CircleDollarSign,
  HandCoins,
  Users,
  Ticket,
  CalendarDays,
  Gavel,
  Globe,
  BarChart3,
  Hash,
  Quote,
  HelpCircle,
  Video,
  MousePointerClick,
  PanelBottom,
  Columns2,
  ListOrdered,
  Timer,
  Sparkles,
  QrCode,
  AppWindow,
  Newspaper,
  PieChart,
  FileText,
  Gift,
  Trophy,
};

export function BlockIcon({ type, className }: { type: BlockType; className?: string }) {
  const Icon = MAP[BLOCK_REGISTRY[type].icon] ?? Square;
  return <Icon className={className} aria-hidden />;
}
